Repository SeaplaGO-Team/Voluntour, pull requests merged in 2018-06, with the labels that each got.

#46 fix some merge issues with admeds new code.
  assets/scripts/script.js
  assets/scripts/testAPIs.js
  index.html
Labels: MergeFix

#47 adding api content to the hmtl
  assets/images/Breezy.png
  assets/images/Cloudy.png
  assets/images/Hail.png
  assets/images/Mist.png
  assets/images/Mostly-sunny.png
  assets/images/Rain.png
  assets/images/Snow-rain.png
  assets/images/Snow.png
  assets/images/Storm.png
  assets/images/Sunny.png
  assets/scripts/script.js
  assets/styles/hover.css
  assets/styles/style.css
  index.html
  package-lock.json
  package.json
Labels: Feature, enhancement

#50 fixed applied to meetup api loop issue
  assets/images/Sunny.png
  assets/scripts/firebase.js
  assets/scripts/script-old.js
  assets/scripts/script.js
  assets/styles/style.css
  index.html
Labels: Feature, bug

#58 updates to UI and cform validation
  index.html
Labels: Feature

#59 new updates and new contact form style
  assets/styles/style.css
  index.html
Labels: UI

#61 :art: changes to meetup style
  assets/scripts/firebase.js
  assets/scripts/script.js
  assets/styles/style.css
Labels: UI

#62 added media queries
  assets/styles/style.css
Labels: UI
